=== seadas/seadas-toolbox/seadas-processing/src/main/resources/gov/nasa/gsfc/seadas/processing/core/ParamInfo-1.0.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="paramInfo">
        <xs:complexType>
            <xs:all>
                <xs:element name="programMetaData" >
                    <xs:complexType>
                        <xs:all>
                            <xs:element name="hasParFile" type="xs:boolean"/>
                            <xs:element name="parFileOptionName" type="xs:string" default="par" minOccurs="0"/>
                            <xs:element name="subPanel0Title" type="xs:string" default="" minOccurs="0"/>
                            <xs:element name="subPanel1Title" type="xs:string" default="" minOccurs="0"/>
                            <xs:element name="subPanel2Title" type="xs:string" default="" minOccurs="0"/>
                            <xs:element name="subPanel3Title" type="xs:string" default="" minOccurs="0"/>
                            <xs:element name="subPanel4Title" type="xs:string" default="" minOccurs="0"/>
                            <xs:element name="numColumns" type="xs:string" default="" minOccurs="0"/>
                            <xs:element name="columnWidth" type="xs:string" default="" minOccurs="0"/>
                            <xs:element name="progressRegex" type="xs:string" minOccurs="0"/>
                            <xs:element name="hasProgramDependency" minOccurs="0">
                                <xs:complexType>
                                    <xs:all>
                                        <xs:element name = "programName"  type="xs:string" />
                                        <xs:element name = "programParamInfo" type="xs:string" />
                                        <xs:element name="isDefault" type="xs:boolean" minOccurs=" 0"/>
                                    </xs:all>
                                </xs:complexType>
                                    </xs:element>
                        </xs:all>
                    </xs:complexType>
                </xs:element>
                <xs:element name="options">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="option" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:all>
                                        <xs:element name="name" type="xs:string"/>
                                        <xs:element name="value" type="xs:string" minOccurs="0">
                                            <xs:alternative test="@type eq 'string'" type="xs:string"/>
                                            <xs:alternative test="@type eq 'int'" type="xs:int"/>
                                            <xs:alternative test="@type eq 'boolean'" type="xs:boolean"/>
                                            <xs:alternative test="@type eq 'float'" type="xs:float"/>
                                            <xs:alternative test="@type eq 'double'" type="xs:double"/>
                                        </xs:element>
                                        <xs:element name="default" type="xs:string" minOccurs="0">
                                            <xs:alternative test="@type eq 'string'" type="xs:string"/>
                                            <xs:alternative test="@type eq 'int'" type="xs:int"/>
                                            <xs:alternative test="@type eq 'boolean'" type="xs:boolean"/>
                                            <xs:alternative test="@type eq 'float'" type="xs:float"/>
                                            <xs:alternative test="@type eq 'double'" type="xs:double"/>
                                        </xs:element>
                                        <xs:element name="source" type="xs:string" minOccurs="0">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="programName" type="xs:string" minOccurs="0"  maxOccurs="1"/>
                                                    <xs:element name="programParamInfo" type="xs:string" minOccurs="0"  maxOccurs="1"/>
                                                </xs:sequence>
                                                <xs:attribute name="isProgram" type="xs:boolean">

                                                </xs:attribute>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="order" type="xs:string" minOccurs="0"/>
                                        <xs:element name="aliases" minOccurs="0">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="alias" type="xs:string" maxOccurs="unbounded"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="validValues" minOccurs="0">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="validValue" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:all>
                                                                <xs:element name="value" type="xs:string">
                                                                    <xs:alternative test="@type eq 'string'"
                                                                                    type="xs:string"/>
                                                                    <xs:alternative test="@type eq 'int'"
                                                                                    type="xs:int"/>
                                                                    <xs:alternative test="@type eq 'boolean'"
                                                                                    type="xs:boolean"/>
                                                                    <xs:alternative test="@type eq 'float'"
                                                                                    type="xs:float"/>
                                                                    <xs:alternative test="@type eq 'double'"
                                                                                    type="xs:double"/>
                                                                </xs:element>
                                                                <xs:element name="description" type="xs:string"/>
                                                            </xs:all>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="description" type="xs:string" minOccurs="0"/>
                                    </xs:all>
                                    <xs:attribute name="type" default="string">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:enumeration value="string"/>
                                                <xs:enumeration value="int"/>
                                                <xs:enumeration value="boolean"/>
                                                <xs:enumeration value="float"/>
                                                <xs:enumeration value="double"/>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                    <xs:attribute name="runtimeOption" type="xs:boolean" default="true"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:all>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== seadas/seadas-toolbox/seadas-processing/src/main/resources/gov/nasa/gsfc/seadas/processing/core/l1bextract_oci.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<paramInfo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="https://seadas.gsfc.nasa.gov/software/schemas/ParamInfo-1.0.xsd">
    <programMetaData>
        <hasParFile>false</hasParFile>
        <parFileOptionName>NO_PAR_FILE</parFileOptionName>
        <primaryOptions>
            <primaryOption>ifile</primaryOption>
            <primaryOption>ofile</primaryOption>
        </primaryOptions>
    </programMetaData>
    <options>
        <option type="ifile">
            <name>ifile</name>
            <value></value>
            <default></default>
            <description>input OCI L1B datafile</description>
            <source>command line</source>
            <usedAs>argument</usedAs>
            <order>0</order>
        </option>
        <option type="int">
            <name>--spixl</name>
            <value></value>
            <default></default>
            <description>start pixel number</description>
            <usedAs>option</usedAs>
            <order>1</order>
        </option>
        <option type="int">
            <name>--epixl</name>
            <value></value>
            <default></default>
            <description>end pixel number</description>
            <usedAs>option</usedAs>
            <order>2</order>
        </option>
        <option type="int">
            <name>--sline</name>
            <value></value>
            <default></default>
            <description>start scan line</description>
            <usedAs>option</usedAs>
            <order>3</order>
        </option>
        <option type="int">
            <name>--eline</name>
            <value></value>
            <default></default>
            <description>end scan line</description>
            <usedAs>option</usedAs>
            <order>4</order>
        </option>
        <option type="ofile">
            <name>ofile</name>
            <value></value>
            <default></default>
            <description>output file name</description>
            <usedAs>argument</usedAs>
            <order>7</order>
        </option>
    </options>
</paramInfo>

=== seadas/seadas-toolbox/seadas-processing/src/main/resources/gov/nasa/gsfc/seadas/processing/core/lonlat2pixline.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<paramInfo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="https://seadas.gsfc.nasa.gov/software/schemas/ParamInfo-1.0.xsd">
    <programMetaData>
        <hasParFile>false</hasParFile>
        <parFileOptionName>NO_PAR_FILE</parFileOptionName>
        <primaryOptions>
            <primaryOption>infile</primaryOption>
        </primaryOptions>
    </programMetaData>
    <options>
        <option type="ifile">
            <name>infile</name>
            <value></value>
            <default></default>
            <description>is either a L1B, L2, or GEO filename</description>
            <source>command line</source>
            <aliases>
                <alias>ifile1</alias>
            </aliases>
            <usedAs>argument</usedAs>
            <order>0</order>
        </option>
        <option type="int">
            <name>West (SWlon)</name>
            <value></value>
            <default></default>
            <description>Longitude of southwest corner of the box to be extracted</description>
            <usedAs>argument</usedAs>
            <order>1</order>
        </option>
        <option type="int">
            <name>South (SWlat)</name>
            <value></value>
            <default></default>
            <description>Latitude of southwest corner of the box to be extracted.</description>
            <usedAs>argument</usedAs>
            <order>2</order>
        </option>
        <option type="int">
            <name>East (NElon)</name>
            <value></value>
            <default></default>
            <description>Longitude of northeast corner of the box to be extracted.</description>
            <usedAs>argument</usedAs>
            <order>3</order>
        </option>
        <option type="int">
            <name>North (NElat)</name>
            <value></value>
            <default></default>
            <description>Latitude of northeast corner of the box to be extracted.</description>
            <usedAs>argument</usedAs>
            <order>4</order>
        </option>
        <option type="help">
            <name>spixl</name>
            <value></value>
            <default></default>
            <description>start pixel number</description>
            <usedAs>argument</usedAs>
            <order>5</order>
        </option>
        <option type="help">
            <name>epixl</name>
            <value></value>
            <default></default>
            <description>end pixel number (-1=the last pixel)</description>
            <usedAs>argument</usedAs>
            <order>6</order>
        </option>
        <option type="help">
            <name>sline</name>
            <value></value>
            <default></default>
            <description>start line number</description>
            <usedAs>argument</usedAs>
            <order>7</order>
        </option>
        <option type="help">
            <name>eline</name>
            <value></value>
            <default></default>
            <description>end line number (-1=the last line)</description>
            <usedAs>argument</usedAs>
            <order>8</order>
        </option>

    </options>
</paramInfo>

=== seadas/seadas-toolbox/seadas-processing/src/main/resources/gov/nasa/gsfc/seadas/processing/core/l1aextract.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<paramInfo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="https://seadas.gsfc.nasa.gov/software/schemas/ParamInfo-1.0.xsd">
    <programMetaData>
        <hasParFile>false</hasParFile>
        <parFileOptionName>NO_PAR_FILE</parFileOptionName>
        <primaryOptions>
            <primaryOption>ifile</primaryOption>
            <primaryOption>ofile</primaryOption>
        </primaryOptions>
    </programMetaData>
    <options>
        <option type="ifile">
            <name>ifile</name>
            <value></value>
            <default></default>
            <description>input MODIS/VIIRS/SewWiFS L1A datafile</description>
            <source>command line</source>
            <aliases>
                <alias>ifile1</alias>
            </aliases>
            <usedAs>argument</usedAs>
            <order>0</order>
        </option>
        <option type="int">
            <name>West (SWlon)</name>
            <value></value>
            <default></default>
            <description>Southwest longitude</description>
            <order>1</order>
<!--            <source>lonlat2pixline</source>-->
            <usedAs>option</usedAs>
        </option>
        <option type="int">
            <name>South (SWlat)</name>
            <value></value>
            <default></default>
            <description>Southwest latitude</description>
            <order>2</order>
<!--            <source>lonlat2pixline</source>-->
            <usedAs>option</usedAs>
        </option>
        <option type="int">
            <name>East (NElon)</name>
            <value></value>
            <default></default>
            <description>Northesat longitude</description>
            <order>3</order>
<!--            <source>lonlat2pixline</source>-->
            <usedAs>option</usedAs>
        </option>
        <option type="int">
            <name>North (NElat)</name>
            <value></value>
            <default></default>
            <description>Northeast latitude</description>
            <order>4</order>
<!--            <source>lonlat2pixline</source>-->
            <usedAs>option</usedAs>
        </option>
        <option type="ofile">
            <name>ofile</name>
            <value></value>
            <default>output</default>
            <description>output extracted file name</description>
            <usedAs>argument</usedAs>
            <order>5</order>
        </option>
    </options>
</paramInfo>

=== seadas/seadas-toolbox/seadas-processing/src/main/resources/gov/nasa/gsfc/seadas/processing/core/l3bindump.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<paramInfo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="https://seadas.gsfc.nasa.gov/software/schemas/ParamInfo-1.0.xsd">
    <programMetaData>
        <hasParFile>true</hasParFile>
        <parFileOptionName>par</parFileOptionName>
        <!--krow:   810 out of   2160  (-22.50 to   0.00) Tue Jun 26 16:14:55 2012-->
        <progressRegex>krow: +(\d+) out of +(\d+)</progressRegex>
        <primaryOptions>
            <primaryOption>ifile</primaryOption>
            <primaryOption>ofile</primaryOption>
        </primaryOptions>
    </programMetaData>
    <options>
        <option type="help">
            <name>-help</name>
            <value>false</value>
            <default>false</default>
            <source>default</source>
            <aliases>
                <alias>-h</alias>
                <alias>--help</alias>
            </aliases>
            <description>print usage information</description>
        </option>
        <option type="help">
            <name>-version</name>
            <value>false</value>
            <default>false</default>
            <source>default</source>
            <aliases>
                <alias>--version</alias>
            </aliases>
            <description>print the version information</description>
        </option>
        <option type="help">
            <name>-dump_options</name>
            <value>false</value>
            <default>false</default>
            <source>default</source>
            <aliases>
                <alias>--dump_options</alias>
            </aliases>
            <description>print information about each option</description>
        </option>
        <option type="help">
            <name>-dump_options_paramfile</name>
            <value>l3bindump_options.txt</value>
            <source>default</source>
            <aliases>
                <alias>--dump_options_paramfile</alias>
            </aliases>
            <description>print information about each option to paramfile</description>
        </option>
        <option type="help">
            <name>-dump_options_xmlfile</name>
            <value>l3bindump_options.xml</value>
            <source>command line</source>
            <aliases>
                <alias>--dump_options_xmlfile</alias>
            </aliases>
            <description>print information about each option to XML file</description>
        </option>
        <option type="help">
            <name>par</name>
            <value/>
            <source>default</source>
            <description>input parameter file</description>
        </option>
        <option type="ifile">
            <name>ifile</name>
            <value></value>
            <source>command line</source>
            <description>input L3 file name</description>
        </option>
        <option type="ofile">
            <name>ofile</name>
            <value>output.txt</value>
            <source>default</source>
            <description>input L3 file name</description>
        </option>
        <option type="string">
            <name>oformat</name>
            <value>txt</value>
            <default>txt</default>
            <source>default</source>
            <validValues>
                <validValue>
                    <value>txt</value>
                    <description>plain text columnar format</description>
                </validValue>
                <validValue>
                    <value>seabass</value>
                    <description>SeaBASS format</description>
                </validValue>
            </validValues>
            <description>output file format</description>
        </option>
        <option type="string">
            <name>l3bprod</name>
            <value></value>
            <default></default>
            <source>default</source>
            <description>binned product to extract</description>
        </option>
        <option type="int">
            <name>bin_number</name>
            <value></value>
            <default></default>
            <source>default</source>
            <description>bin number</description>
        </option>
        <option type="float">
            <name>north</name>
            <value></value>
            <default></default>
            <source>default</source>
            <description>north boundary</description>
        </option>
        <option type="float">
            <name>south</name>
            <value></value>
            <default></default>
            <source>default</source>
            <description>south boundary</description>
        </option>
        <option type="float">
            <name>east</name>
            <value></value>
            <default></default>
            <source>default</source>
            <description>east boundary</description>
        </option>
        <option type="float">
            <name>west</name>
            <value></value>
            <default></default>
            <source>default</source>
            <description>west boundary</description>
        </option>
        <option type="float">
            <name>lat</name>
            <value></value>
            <default></default>
            <source>default</source>
            <description>latitude</description>
        </option>
        <option type="float">
            <name>lon</name>
            <value></value>
            <default></default>
            <source>default</source>
            <description>longitude</description>
        </option>
        <option type="float">
            <name>radius</name>
            <value></value>
            <default></default>
            <source>default</source>
            <description>radius</description>
        </option>
        <option type="boolean">
            <name>verbose</name>
            <value></value>
            <default></default>
            <source>default</source>
            <description>verbose output</description>
        </option>
    </options>
</paramInfo>
